import { Component } from '@angular/core';
import {
  IonApp,
  IonRouterOutlet,
} from '@ionic/angular/standalone';

import { addIcons } from 'ionicons';

import {
  airplaneOutline,
  alertCircleOutline,
  bluetoothOutline,
  bookmarkOutline,
  cameraOutline,
  cameraReverseOutline,
  checkmarkCircle,
  chevronDownOutline,
  chevronForwardOutline,
  chevronUpOutline,
  closeCircle,
  closeOutline,
  cloudOfflineOutline,
  constructOutline,
  copyOutline,
  createOutline,
  documentTextOutline,
  ellipseOutline,
  gridOutline,
  hardwareChipOutline,
  headsetOutline,
  heart,
  heartOutline,
  helpCircleOutline,
  homeOutline,
  hourglassOutline,
  imageOutline,
  informationCircleOutline,
  keyOutline,
  linkOutline,
  locateOutline,
  locationOutline,
  mapOutline,
  moonOutline,
  musicalNotesOutline,
  navigateOutline,
  notificationsOutline,
  openOutline,
  optionsOutline,
  pause,
  phonePortraitOutline,
  play,
  pricetagOutline,
  qrCodeOutline,
  searchOutline,
  serverOutline,
  shieldCheckmarkOutline,
  starOutline,
  stop,
  sunnyOutline,
  timeOutline,
  trashOutline,
  wifiOutline,
  eyeOffOutline,
eyeOutline,
lockClosedOutline,
logInOutline,
logoGoogle,
mailOutline,
personAddOutline,
personOutline,
} from 'ionicons/icons';

import { ThemeService } from './services/theme';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  standalone: true,
  imports: [
    IonApp,
    IonRouterOutlet,
  ],
})
export class AppComponent {
  constructor(
    private readonly themeService: ThemeService
  ) {
    addIcons({
      airplaneOutline,
      alertCircleOutline,
      bluetoothOutline,
      bookmarkOutline,
      cameraOutline,
      cameraReverseOutline,
      checkmarkCircle,
      chevronDownOutline,
      chevronForwardOutline,
      chevronUpOutline,
      closeCircle,
      closeOutline,
      cloudOfflineOutline,
      constructOutline,
      copyOutline,
      createOutline,
      documentTextOutline,
      ellipseOutline,
      gridOutline,
      hardwareChipOutline,
      headsetOutline,
      heart,
      heartOutline,
      helpCircleOutline,
      homeOutline,
      hourglassOutline,
      imageOutline,
      informationCircleOutline,
      keyOutline,
      linkOutline,
      locateOutline,
      locationOutline,
      mapOutline,
      moonOutline,
      musicalNotesOutline,
      navigateOutline,
      notificationsOutline,
      openOutline,
      optionsOutline,
      pause,
      phonePortraitOutline,
      play,
      pricetagOutline,
      qrCodeOutline,
      searchOutline,
      serverOutline,
      shieldCheckmarkOutline,
      starOutline,
      stop,
      sunnyOutline,
      timeOutline,
      trashOutline,
      wifiOutline,
      eyeOffOutline,
eyeOutline,
lockClosedOutline,
logInOutline,
logoGoogle,
mailOutline,
personAddOutline,
personOutline,
    });

    void this.themeService.initialize();
  }
}